//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from UMLDiagram.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="UMLDiagramParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IUMLDiagramVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.diagram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiagram([NotNull] UMLDiagramParser.DiagramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] UMLDiagramParser.ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.classDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDefinition([NotNull] UMLDiagramParser.ClassDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBody([NotNull] UMLDiagramParser.ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassMember([NotNull] UMLDiagramParser.ClassMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod([NotNull] UMLDiagramParser.MethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] UMLDiagramParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.methodArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodArguments([NotNull] UMLDiagramParser.MethodArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.methodArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodArgument([NotNull] UMLDiagramParser.MethodArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelation([NotNull] UMLDiagramParser.RelationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.relationType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationType([NotNull] UMLDiagramParser.RelationTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility([NotNull] UMLDiagramParser.VisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassName([NotNull] UMLDiagramParser.ClassNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodName([NotNull] UMLDiagramParser.MethodNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.argumentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentName([NotNull] UMLDiagramParser.ArgumentNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] UMLDiagramParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.attributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeName([NotNull] UMLDiagramParser.AttributeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UMLDiagramParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] UMLDiagramParser.TypeContext context);
}
