//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from UMLDiagram.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class UMLDiagramLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, NAME=20, COMMENT=21, WHITE_SPACE=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "T__18", "NAME", "COMMENT", "WHITE_SPACE"
	};


	public UMLDiagramLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public UMLDiagramLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'@startuml'", "'@enduml'", "'class'", "'{'", "'}'", "'('", "')'", 
		"':'", "','", "'<|..'", "'-->'", "'<--'", "'<-->'", "'--'", "'..>'", "'<|--'", 
		"'+'", "'-'", "'#'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "NAME", "COMMENT", "WHITE_SPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "UMLDiagram.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static UMLDiagramLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x18', '\x8E', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', 
		'\a', '\x15', 'z', '\n', '\x15', '\f', '\x15', '\xE', '\x15', '}', '\v', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\a', 
		'\x16', '\x83', '\n', '\x16', '\f', '\x16', '\xE', '\x16', '\x86', '\v', 
		'\x16', '\x3', '\x17', '\x6', '\x17', '\x89', '\n', '\x17', '\r', '\x17', 
		'\xE', '\x17', '\x8A', '\x3', '\x17', '\x3', '\x17', '\x2', '\x2', '\x18', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', 
		'#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', 
		'\x18', '\x3', '\x2', '\x6', '\x4', '\x2', '\x43', '\\', '\x63', '|', 
		'\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x5', '\x2', '\v', '\f', '\xF', 
		'\xF', '\"', '\"', '\x2', '\x90', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x5', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\a', '\x41', '\x3', '\x2', '\x2', '\x2', '\t', 'G', '\x3', '\x2', '\x2', 
		'\x2', '\v', 'I', '\x3', '\x2', '\x2', '\x2', '\r', 'K', '\x3', '\x2', 
		'\x2', '\x2', '\xF', 'M', '\x3', '\x2', '\x2', '\x2', '\x11', 'O', '\x3', 
		'\x2', '\x2', '\x2', '\x13', 'Q', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'S', '\x3', '\x2', '\x2', '\x2', '\x17', 'X', '\x3', '\x2', '\x2', '\x2', 
		'\x19', '\\', '\x3', '\x2', '\x2', '\x2', '\x1B', '`', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x65', '\x3', '\x2', '\x2', '\x2', '\x1F', 'h', '\x3', 
		'\x2', '\x2', '\x2', '!', 'l', '\x3', '\x2', '\x2', '\x2', '#', 'q', '\x3', 
		'\x2', '\x2', '\x2', '%', 's', '\x3', '\x2', '\x2', '\x2', '\'', 'u', 
		'\x3', '\x2', '\x2', '\x2', ')', 'w', '\x3', '\x2', '\x2', '\x2', '+', 
		'~', '\x3', '\x2', '\x2', '\x2', '-', '\x88', '\x3', '\x2', '\x2', '\x2', 
		'/', '\x30', '\a', '\x42', '\x2', '\x2', '\x30', '\x31', '\a', 'u', '\x2', 
		'\x2', '\x31', '\x32', '\a', 'v', '\x2', '\x2', '\x32', '\x33', '\a', 
		'\x63', '\x2', '\x2', '\x33', '\x34', '\a', 't', '\x2', '\x2', '\x34', 
		'\x35', '\a', 'v', '\x2', '\x2', '\x35', '\x36', '\a', 'w', '\x2', '\x2', 
		'\x36', '\x37', '\a', 'o', '\x2', '\x2', '\x37', '\x38', '\a', 'n', '\x2', 
		'\x2', '\x38', '\x4', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', '\x42', 
		'\x2', '\x2', ':', ';', '\a', 'g', '\x2', '\x2', ';', '<', '\a', 'p', 
		'\x2', '\x2', '<', '=', '\a', '\x66', '\x2', '\x2', '=', '>', '\a', 'w', 
		'\x2', '\x2', '>', '?', '\a', 'o', '\x2', '\x2', '?', '@', '\a', 'n', 
		'\x2', '\x2', '@', '\x6', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', 
		'\a', '\x65', '\x2', '\x2', '\x42', '\x43', '\a', 'n', '\x2', '\x2', '\x43', 
		'\x44', '\a', '\x63', '\x2', '\x2', '\x44', '\x45', '\a', 'u', '\x2', 
		'\x2', '\x45', '\x46', '\a', 'u', '\x2', '\x2', '\x46', '\b', '\x3', '\x2', 
		'\x2', '\x2', 'G', 'H', '\a', '}', '\x2', '\x2', 'H', '\n', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'J', '\a', '\x7F', '\x2', '\x2', 'J', '\f', '\x3', 
		'\x2', '\x2', '\x2', 'K', 'L', '\a', '*', '\x2', '\x2', 'L', '\xE', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'N', '\a', '+', '\x2', '\x2', 'N', '\x10', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'P', '\a', '<', '\x2', '\x2', 'P', '\x12', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'R', '\a', '.', '\x2', '\x2', 'R', '\x14', '\x3', 
		'\x2', '\x2', '\x2', 'S', 'T', '\a', '>', '\x2', '\x2', 'T', 'U', '\a', 
		'~', '\x2', '\x2', 'U', 'V', '\a', '\x30', '\x2', '\x2', 'V', 'W', '\a', 
		'\x30', '\x2', '\x2', 'W', '\x16', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', 
		'\a', '/', '\x2', '\x2', 'Y', 'Z', '\a', '/', '\x2', '\x2', 'Z', '[', 
		'\a', '@', '\x2', '\x2', '[', '\x18', '\x3', '\x2', '\x2', '\x2', '\\', 
		']', '\a', '>', '\x2', '\x2', ']', '^', '\a', '/', '\x2', '\x2', '^', 
		'_', '\a', '/', '\x2', '\x2', '_', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x61', '\a', '>', '\x2', '\x2', '\x61', '\x62', '\a', '/', '\x2', 
		'\x2', '\x62', '\x63', '\a', '/', '\x2', '\x2', '\x63', '\x64', '\a', 
		'@', '\x2', '\x2', '\x64', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x66', '\a', '/', '\x2', '\x2', '\x66', 'g', '\a', '/', '\x2', '\x2', 
		'g', '\x1E', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\a', '\x30', '\x2', 
		'\x2', 'i', 'j', '\a', '\x30', '\x2', '\x2', 'j', 'k', '\a', '@', '\x2', 
		'\x2', 'k', ' ', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '>', '\x2', 
		'\x2', 'm', 'n', '\a', '~', '\x2', '\x2', 'n', 'o', '\a', '/', '\x2', 
		'\x2', 'o', 'p', '\a', '/', '\x2', '\x2', 'p', '\"', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\a', '-', '\x2', '\x2', 'r', '$', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\a', '/', '\x2', '\x2', 't', '&', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'v', '\a', '%', '\x2', '\x2', 'v', '(', '\x3', '\x2', '\x2', 
		'\x2', 'w', '{', '\t', '\x2', '\x2', '\x2', 'x', 'z', '\t', '\x3', '\x2', 
		'\x2', 'y', 'x', '\x3', '\x2', '\x2', '\x2', 'z', '}', '\x3', '\x2', '\x2', 
		'\x2', '{', 'y', '\x3', '\x2', '\x2', '\x2', '{', '|', '\x3', '\x2', '\x2', 
		'\x2', '|', '*', '\x3', '\x2', '\x2', '\x2', '}', '{', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x7F', '\a', '\x31', '\x2', '\x2', '\x7F', '\x80', '\a', 
		'\x31', '\x2', '\x2', '\x80', '\x84', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x83', '\n', '\x4', '\x2', '\x2', '\x82', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x86', '\x3', '\x2', '\x2', '\x2', '\x84', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x85', '\x3', '\x2', '\x2', '\x2', '\x85', 
		',', '\x3', '\x2', '\x2', '\x2', '\x86', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x89', '\t', '\x5', '\x2', '\x2', '\x88', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\b', 
		'\x17', '\x2', '\x2', '\x8D', '.', '\x3', '\x2', '\x2', '\x2', '\x6', 
		'\x2', '{', '\x84', '\x8A', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
