//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from UMLDiagram.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AnimArch.UMLDiagram.Generated {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="UMLDiagramParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IUMLDiagramListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.diagram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiagram([NotNull] UMLDiagramParser.DiagramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.diagram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiagram([NotNull] UMLDiagramParser.DiagramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] UMLDiagramParser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] UMLDiagramParser.ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.classDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDefinition([NotNull] UMLDiagramParser.ClassDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.classDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDefinition([NotNull] UMLDiagramParser.ClassDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] UMLDiagramParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] UMLDiagramParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassMember([NotNull] UMLDiagramParser.ClassMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassMember([NotNull] UMLDiagramParser.ClassMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod([NotNull] UMLDiagramParser.MethodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod([NotNull] UMLDiagramParser.MethodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.methodArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodArguments([NotNull] UMLDiagramParser.MethodArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.methodArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodArguments([NotNull] UMLDiagramParser.MethodArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.methodArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodArgument([NotNull] UMLDiagramParser.MethodArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.methodArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodArgument([NotNull] UMLDiagramParser.MethodArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelation([NotNull] UMLDiagramParser.RelationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelation([NotNull] UMLDiagramParser.RelationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.relationType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationType([NotNull] UMLDiagramParser.RelationTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.relationType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationType([NotNull] UMLDiagramParser.RelationTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibility([NotNull] UMLDiagramParser.VisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibility([NotNull] UMLDiagramParser.VisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassName([NotNull] UMLDiagramParser.ClassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassName([NotNull] UMLDiagramParser.ClassNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodName([NotNull] UMLDiagramParser.MethodNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodName([NotNull] UMLDiagramParser.MethodNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.argumentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentName([NotNull] UMLDiagramParser.ArgumentNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.argumentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentName([NotNull] UMLDiagramParser.ArgumentNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnType([NotNull] UMLDiagramParser.ReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnType([NotNull] UMLDiagramParser.ReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] UMLDiagramParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] UMLDiagramParser.TypeContext context);
}
} // namespace AnimArch.UMLDiagram.Generated
