//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from UMLDiagram.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IUMLDiagramListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class UMLDiagramBaseListener : IUMLDiagramListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.diagram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiagram([NotNull] UMLDiagramParser.DiagramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.diagram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiagram([NotNull] UMLDiagramParser.DiagramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] UMLDiagramParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] UMLDiagramParser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.classDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDefinition([NotNull] UMLDiagramParser.ClassDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.classDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDefinition([NotNull] UMLDiagramParser.ClassDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] UMLDiagramParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] UMLDiagramParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.classMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassMember([NotNull] UMLDiagramParser.ClassMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.classMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassMember([NotNull] UMLDiagramParser.ClassMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod([NotNull] UMLDiagramParser.MethodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod([NotNull] UMLDiagramParser.MethodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.methodArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodArguments([NotNull] UMLDiagramParser.MethodArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.methodArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodArguments([NotNull] UMLDiagramParser.MethodArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.methodArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodArgument([NotNull] UMLDiagramParser.MethodArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.methodArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodArgument([NotNull] UMLDiagramParser.MethodArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelation([NotNull] UMLDiagramParser.RelationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelation([NotNull] UMLDiagramParser.RelationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.relationType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationType([NotNull] UMLDiagramParser.RelationTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.relationType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationType([NotNull] UMLDiagramParser.RelationTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVisibility([NotNull] UMLDiagramParser.VisibilityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVisibility([NotNull] UMLDiagramParser.VisibilityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassName([NotNull] UMLDiagramParser.ClassNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassName([NotNull] UMLDiagramParser.ClassNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.methodName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodName([NotNull] UMLDiagramParser.MethodNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.methodName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodName([NotNull] UMLDiagramParser.MethodNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.argumentName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentName([NotNull] UMLDiagramParser.ArgumentNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.argumentName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentName([NotNull] UMLDiagramParser.ArgumentNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnType([NotNull] UMLDiagramParser.ReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnType([NotNull] UMLDiagramParser.ReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UMLDiagramParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] UMLDiagramParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UMLDiagramParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] UMLDiagramParser.TypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
